<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
 'Home' => '首页',
'create' => '创建', 
'logo_error' => "用户名或者密码不能为空",
'logo_success' => "登录成功",
'logo_error' => "用户名或者密码错误",
'v_error' => "验证码错误",
'success' => "操作成功",
'error' => "操作失败",
'frist_page' => "第一页",
'last_page' => "尾页",
'prev_page' => "上一页",
'next_page' => "下一页",
'setting' => "站点设置",
'language' => "语言管理",
'db' => "数据库管理",
'site_name' => "zh站点名称",
'picture' => "图片",
'selecttype' => "选择分类",
'type' => "分类",
'look' => "查看",
'operation' => "操作",
'remark' => "备注",
//'type' => "类型",
'select'=>'请选择',
'all' => "全选",
'list' => "列表",
'lists' => "列表",
'typelists' => "分类列表",
'add' => "添加",
'del' => "删除",
'order' => "排序",
'edit' => "编辑",
'status' => "状态",
'state_1' => "启动",
'state_2' => "禁用",
'submit' => "提交",
'down' => "下载",
'article' => "文章",
'helps' => "帮助中心",
'fragment' => "碎片",
'hits' => "点击量",
'createtime' => "创建时间",
'tpl' => "模板",
'auther' => "作者",
'copyfrom' => "来源",
'pic' => "图片",
'pics' => "图片列表",

'mysql_sql' => "mysql语句",
'sqlcmd' => "sql命令行",
'sqldown' => "备份下载",

'table_name' => "数据表",
'table_type' => "类型",
'table_row' => "记录数",
'table_size' => "数据大小",
'table_index' => "索引",
'table_free' => "碎片",


'no_checked' => "没有选中项",

'need_time' => "操作需要一些时间，请稍等",


'category_name'=>'分类名称',
'category_model'=>'模型',
'out_link'=>'外部链接',
'yes'=>'是',
'no'=>'否',
'alias'=>'别名',
'links'=>'链接',
'parent'=>'父类',

'isnav'=>'是否导航显示',


'page'=>'单页',
'title'=>'标题',
'keywords'=>'关键字',
'description'=>'描述',
'content'=>'内容',
'name'=>'名称',
'email'=>'电子邮件',
'phone'=>'手机号码',

'pagesize'=>'分页条数',
'tpl_list'=>'列表模板',
'tpl_detail'=>'内容模板',


'seo'=>'seo',
'target'=>'target',
'_self'=>'_self',
'_blank'=>'_blank',

'upload_pic'=>'上传图片',






'cms'=>'内容管理系统',
'system'=>'系统',
'other'=>'其他',
'category'=>'栏目',
'content'=>'内容',
'member'=>'用户',
'membergroup'=>'用户分组',
'permission'=>'认证权限',
'cacher'=>'缓存管理',
'friendlink'=>'友情链接',
'guestbook'=>'留言板',
'nav'=>'导航',
'slider'=>'幻灯片',
'ads'=>'广告',
'model'=>'模块',
'manage'=>'管理',

'language'=>'语言',

'index'=>'首页',
'backup'=>'备份',
'optimize'=>'优化',
'download'=>'下载',
'mysqlcmd'=>'mysqlcmd',

'pics_del'=>'删除图片',
'pics_edit'=>'编辑图片',

);
