<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Contact' => '联系我们',
  'Contact Us'=>'联系我们',
  'Enlish Evn'=>'英语环境',
  'Chinese Evn'=>'中文环境',
  'start'=>'起步',
  'widgets'=>'小工具',
  'components'=>'组件',
  'cli'=>'命令行',
  'extra'=>'其它',
  'extra topic'=>'其它主题',
  'URL manager'=>'URL管理',
  'subject & skin'=>'主题与皮肤',
  'I18n'=>'国际化',
  'are required.'=>'是必须填写的.',
  'Fields with'=>'表单带有',
  'If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.' => '有任何问题请与我们联系,谢谢.',
  'Name'=>'姓名',
  'Email'=>'邮件地址',
  'Subject'=>'主题',
  'Body'=>'内容',
  'Verification Code'=>'验证码',
  'Please enter the letters as they are shown in the image above.<br/>Letters are not case-sensitive.'=>'请输入上图展示的验证码,大小写无关'
);
